name: Arduino-lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          project-type: all
          recursive: true
          compliance: permissive
          library-manager: false
